2022-01-05 13:14:34.160008 HTTPConnectionPool(host='%22+my_https+%22', port=80): Max retries exceeded with url: /api/gpslogger?data=[%7B%20%22HubId%22:29,%20%22Latitude%22:%220%22,%20%22Longitude%22:%220%22,%20%22Altitude%22:%2225%22,%20%22Speed%22:0,%20%22ServerDateTime%22:%222022-01-05%2013:14:34%22%20%7D%20] (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x747ac670>: Failed to establish a new connection: [Errno -2] Name or service not known'))